DATALOADER:
  TRAIN_X:
    SAMPLER: "SeqDomainSampler"
    BATCH_SIZE: 129
  TRAIN_U:
    SAME_AS_X: True
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8
  RETURN_IMG0: True

OPTIM:
  NAME: "sgd"
  LR: 0.05
  STEPSIZE: [20]
  MAX_EPOCH: 50

TRAIN:
  COUNT_ITER: "train_u"
  PRINT_FREQ: 20

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ["random_flip", "randaugment_fixmatch", "normalize", "cutout"]
